name: Create Package

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  arm64_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
        
    - name: CMake build and run
      run: |
        docker run --platform linux/arm64/v8 --rm -v "${{ github.workspace }}":/build -w /build arm64v8/gcc bash -c "apt update && apt install -y cmake libpaho-mqtt1.3; mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . -j $(nproc) && cpack"
        
    - uses: actions/upload-artifact@v2
      with:
        name: ve2mqtt.deb
        path: |
          ${{ github.workspace }}/build/ve2mqtt-*.deb

    - name: Upload to S3
      run: |
        echo "host_base = s3.womolin.de" > ~/.s3cfg
        echo "host_bucket = s3.womolin.de" >> ~/.s3cfg
        echo "bucket_location = de-fra" >> ~/.s3cfg
        echo "use_https = True" >> ~/.s3cfg
        echo "access_key = ${{ secrets.S3_ACCESS_KEY }}" >> ~/.s3cfg
        echo "secret_key = ${{ secrets.S3_SECRET_KEY }}" >> ~/.s3cfg
        echo "signature_v2 = False" >> ~/.s3cfg
        sudo apt -y update
        sudo apt -y install s3cmd
        s3cmd put ${{ github.workspace }}/build/ve2mqtt-*.deb s3://ve2mqtt/
